# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JdBuyerAppProUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.AddPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddPushButton.setGeometry(QtCore.QRect(270, 570, 131, 31))
        self.AddPushButton.setObjectName("AddPushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 570, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AreaIdlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AreaIdlineEdit.setGeometry(QtCore.QRect(80, 570, 181, 31))
        self.AreaIdlineEdit.setObjectName("AreaIdlineEdit")
        self.RunPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunPushButton.setGeometry(QtCore.QRect(660, 570, 131, 31))
        self.RunPushButton.setObjectName("RunPushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 570, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(90, 610, 171, 31))
        self.PasswordLineEdit.setText("")
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 610, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddPushButton.setText(_translate("MainWindow", "添加新商品"))
        self.label.setText(_translate("MainWindow", "地区ID:"))
        self.RunPushButton.setText(_translate("MainWindow", "开始运行"))
        self.label_2.setText(_translate("MainWindow", "当前登录状态:N/A"))
        self.label_3.setText(_translate("MainWindow", "支付密码:"))
