# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TabSubWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(689, 455)
        self.DelPushButton = QtWidgets.QPushButton(Form)
        self.DelPushButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.DelPushButton.setObjectName("DelPushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SkuLineEdit = QtWidgets.QLineEdit(Form)
        self.SkuLineEdit.setGeometry(QtCore.QRect(80, 70, 171, 31))
        self.SkuLineEdit.setObjectName("SkuLineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 119, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.BusyNumHorizontalSlider = QtWidgets.QSlider(Form)
        self.BusyNumHorizontalSlider.setGeometry(QtCore.QRect(180, 120, 71, 31))
        self.BusyNumHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BusyNumHorizontalSlider.setObjectName("BusyNumHorizontalSlider")
        self.InvenQueryInterHorizontalSlider = QtWidgets.QSlider(Form)
        self.InvenQueryInterHorizontalSlider.setGeometry(QtCore.QRect(470, 121, 71, 31))
        self.InvenQueryInterHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.InvenQueryInterHorizontalSlider.setObjectName("InvenQueryInterHorizontalSlider")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(300, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.RegularRushStartTimeEdit = QtWidgets.QTimeEdit(Form)
        self.RegularRushStartTimeEdit.setGeometry(QtCore.QRect(130, 210, 118, 31))
        self.RegularRushStartTimeEdit.setObjectName("RegularRushStartTimeEdit")
        self.RegularRushCheckBox = QtWidgets.QCheckBox(Form)
        self.RegularRushCheckBox.setGeometry(QtCore.QRect(10, 170, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RegularRushCheckBox.setFont(font)
        self.RegularRushCheckBox.setObjectName("RegularRushCheckBox")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.RegularRushKeepTimeHorizontalSlider = QtWidgets.QSlider(Form)
        self.RegularRushKeepTimeHorizontalSlider.setGeometry(QtCore.QRect(430, 211, 141, 31))
        self.RegularRushKeepTimeHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegularRushKeepTimeHorizontalSlider.setObjectName("RegularRushKeepTimeHorizontalSlider")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DelPushButton.setText(_translate("Form", "删除本商品"))
        self.label.setText(_translate("Form", "商品SKU:"))
        self.label_2.setText(_translate("Form", "商品购买数量:N/A个:"))
        self.label_3.setText(_translate("Form", "库存查询间隔N/A秒:"))
        self.RegularRushCheckBox.setText(_translate("Form", "商品为定时抢购商品"))
        self.label_4.setText(_translate("Form", "抢购开始时间:"))
        self.label_5.setText(_translate("Form", "抢购持续时长N/A秒:"))
        self.label_7.setText(_translate("Form", "当前状态:N/A"))
